package net.amcintosh.freshbooks.resources;

import com.google.api.client.http.HttpMethods;
import com.google.common.collect.ImmutableMap;
import net.amcintosh.freshbooks.FreshBooksClient;
import net.amcintosh.freshbooks.FreshBooksException;
import net.amcintosh.freshbooks.models.*;
import net.amcintosh.freshbooks.models.api.AccountingListResponse;
import net.amcintosh.freshbooks.models.api.AccountingResponse;
import net.amcintosh.freshbooks.models.builders.IncludesQueryBuilder;
import net.amcintosh.freshbooks.models.builders.QueryBuilder;
import net.amcintosh.freshbooks.resources.api.AccountingResource;

import java.util.List;
import java.util.Map;

public class Payments extends AccountingResource {

    public Payments(FreshBooksClient freshBooksClient) {
        super(freshBooksClient);
    }

    @Override
    protected String getPath() {
        return "payments/payments";
    }

    /**
     * Get a list of payments using the query strings generated by the QueryBuilder list.
     *
     * @param accountId Id of the account
     * @return PaymentList containing payments and pagination details
     * @throws FreshBooksException If the call is not successful
     */
    public PaymentList list(String accountId) throws FreshBooksException {
        return this.list(accountId, null);
    }

    /**
     * Get a list of payments using the query strings generated by the QueryBuilder list.
     *
     * @param accountId Id of the account
     * @param builders List of QueryBuilders
     * @return PaymentList containing payments and pagination details
     * @throws FreshBooksException If the call is not successful
     */
    public PaymentList list(String accountId, List<QueryBuilder> builders) throws FreshBooksException {
        String url = this.getUrl(accountId, builders);
        AccountingListResponse result = this.handleListRequest(url);
        return new PaymentList(result.response.result);
    }

    /**
     * Get a single payment with the corresponding id.
     *
     * @param accountId The alpha-numeric account id
     * @param paymentId Id of the resource to return
     *
     * @return The Payment
     * @throws FreshBooksException If the call is not successful
     */
    public Payment get(String accountId, long paymentId) throws FreshBooksException {
        return this.get(accountId, paymentId, null);
    }

    /**
     * Get a single payment with the corresponding id.
     *
     * @param accountId The alpha-numeric account id
     * @param paymentId Id of the resource to return
     * @param builder IncludesQueryBuilder object for including additional data, sub-resources, etc.
     *
     * @return The Payment
     * @throws FreshBooksException If the call is not successful
     */
    public Payment get(String accountId, long paymentId, IncludesQueryBuilder builder) throws FreshBooksException {
        String url = this.getUrl(accountId, paymentId, builder);
        AccountingResponse result = this.handleRequest(HttpMethods.GET, url);
        return result.response.result.payment;
    }

    /**
     * Create a new payment from the provided Payment model.
     * Makes a POST call against the payment resource endpoint.
     *
     * This calls `payment.getContent()` to get a hash map of data.
     *
     * @param accountId The alpha-numeric account id
     * @param data Payment model with create data
     *
     * @return The created Payment
     * @throws FreshBooksException If the call is not successful
     */
    public Payment create(String accountId, Payment data) throws FreshBooksException {
        return this.create(accountId, data.getContent());
    }

    /**
     * Create a new payment from the provided data.
     * Makes a POST call against the payment resource endpoint.
     *
     * @param accountId The alpha-numeric account id
     * @param data Map of create data
     *
     * @return The created Payment
     * @throws FreshBooksException If the call is not successful
     */
    public Payment create(String accountId, Map<String, Object> data) throws FreshBooksException {
        String url = this.getUrl(accountId);
        ImmutableMap<String, Object> content = ImmutableMap.of("payment", data);
        AccountingResponse result = this.handleRequest(HttpMethods.POST, url, content);
        return result.response.result.payment;
    }

    /**
     * Update the payment with the corresponding id.
     * Makes a PUT call against the payment resource endpoint.
     *
     * @param accountId The alpha-numeric account id
     * @param paymentId Id of the resource to return
     * @param data Payment model with updated data
     *
     * @return The updated Payment
     * @throws FreshBooksException If the call is not successful
     */
    public Payment update(String accountId, long paymentId, Payment data) throws FreshBooksException {
        return this.update(accountId, paymentId, data.getContent());
    }

    /**
     * Update the payment with the corresponding id.
     * Makes a PUT call against the payment resource endpoint.
     *
     * @param accountId The alpha-numeric account id
     * @param paymentId Id of the resource to update
     * @param data Map of data to change
     *
     * @return The updated Payment
     * @throws FreshBooksException If the call is not successful
     */
    public Payment update(String accountId, long paymentId, Map<String, Object> data) throws FreshBooksException {
        String url = this.getUrl(accountId, paymentId);
        ImmutableMap<String, Object> content = ImmutableMap.of("payment", data);
        AccountingResponse result = this.handleRequest(HttpMethods.PUT, url, content);
        return result.response.result.payment;
    }

    /**
     * Delete the payment with the corresponding id.
     * Makes a PUT call against the payment resource endpoint with a `vis_state` of deleted.
     * <br><br>
     * <i>Note:</i> Most FreshBooks resources are soft-deleted,
     * @see <a href="https://www.freshbooks.com/api/active_deleted">FreshBooks API - Active and Deleted Objects</a>
     *
     * @param accountId The alpha-numeric account id
     * @param paymentId Id of the resource to update
     *
     * @return The deleted Payment
     * @throws FreshBooksException If the call is not successful
     */
    public Payment delete(String accountId, long paymentId) throws FreshBooksException {
        ImmutableMap<String, Object> data = ImmutableMap.of("vis_state", VisState.DELETED.getValue());
        return this.update(accountId, paymentId, data);
    }
}
