package net.amcintosh.freshbooks.resources;

import com.google.api.client.http.HttpMethods;
import com.google.common.collect.ImmutableMap;
import net.amcintosh.freshbooks.FreshBooksClient;
import net.amcintosh.freshbooks.FreshBooksException;
import net.amcintosh.freshbooks.models.Service;
import net.amcintosh.freshbooks.models.ServiceList;
import net.amcintosh.freshbooks.models.api.ProjectListResponse;
import net.amcintosh.freshbooks.models.api.ProjectResponse;
import net.amcintosh.freshbooks.models.builders.IncludesQueryBuilder;
import net.amcintosh.freshbooks.models.builders.QueryBuilder;
import net.amcintosh.freshbooks.resources.api.CommentResource;

import java.util.List;
import java.util.Map;

/**
 * FreshBooks services resource with calls to get, list, create, update, delete
 */
public class Services extends CommentResource {

    public Services(FreshBooksClient freshBooksClient) {
        super(freshBooksClient);
    }

    @Override
    protected String getPathForSingle() {
        return "service";
    }

    @Override
    protected String getPathForList() {
        return "services";
    }

    /**
     * Get a list of services.
     *
     * @param businessId Id of the business
     * @return ServiceList containing services and pagination details
     * @throws FreshBooksException If the call is not successful
     */
    public ServiceList list(long businessId) throws FreshBooksException {
        return list(businessId, null);
    }

    /**
     * Get a list of services using the query strings generated by the QueryBuilder list.
     *
     * @param businessId Id of the business
     * @param builders List of QueryBuilders
     * @return ServiceList containing services and pagination details
     * @throws FreshBooksException If the call is not successful
     */
    public ServiceList list(long businessId, List<QueryBuilder> builders) throws FreshBooksException {
        String url = this.getUrl(businessId, true, builders);
        ProjectListResponse result = this.handleListRequest(url);
        return new ServiceList(result);

    }

    /**
     * Get a single service with the corresponding id.
     *
     * @param businessId The alpha-numeric business id
     * @param serviceId Id of the resource to return
     *
     * @return The Service
     * @throws FreshBooksException If the call is not successful
     */
    public Service get(long businessId, long serviceId) throws FreshBooksException {
        return this.get(businessId, serviceId, null);
    }

    /**
     * Get a single service with the corresponding id.
     *
     * @param businessId The alpha-numeric business id
     * @param serviceId Id of the resource to return
     * @param builder IncludesQueryBuilder object for including additional data, sub-resources, etc.
     *
     * @return The Service
     * @throws FreshBooksException If the call is not successful
     */
    public Service get(long businessId, long serviceId, IncludesQueryBuilder builder) throws FreshBooksException {
        String url = this.getUrl(businessId, serviceId, builder);
        ProjectResponse result = this.handleRequest(HttpMethods.GET, url);
        return result.service;
    }

    /**
     * Create a new service from the provided Service model.
     * Makes a POST call against the service resource endpoint.
     *
     * This calls `service.getContent()` to get a hash map of data.
     *
     * @param businessId The numeric business id
     * @param data Service model with create data
     *
     * @return The created Service
     * @throws FreshBooksException If the call is not successful
     */
    public Service create(long businessId, Service data) throws FreshBooksException {
        return create(businessId, data.getContent());
    }

    /**
     * Create a new service from the provided data.
     * Makes a POST call against the service resource endpoint.
     *
     * @param businessId The numeric business id
     * @param data Map of create data
     *
     * @return The created Service
     * @throws FreshBooksException If the call is not successful
     */
    public Service create(long businessId, Map<String, Object> data) throws FreshBooksException {
        String url = this.getUrl(businessId, false);
        ImmutableMap<String, Object> content = ImmutableMap.of("service", data);
        ProjectResponse result = this.handleRequest(HttpMethods.POST, url, content);
        return result.service;
    }

    /**
     * Update the service with the corresponding id.
     * Makes a PUT call against the service resource endpoint.
     *
     * @param businessId Id of the business
     * @param serviceId Id of the resource to update
     * @param data Project model with updated data
     *
     * @return The updated Service
     * @throws FreshBooksException If the call is not successful
     */
    public Service update(long businessId, long serviceId, Service data) throws FreshBooksException {
        return this.update(businessId, serviceId, data.getContent());
    }

    /**
     * Update the service with the corresponding id.
     * Makes a PUT call against the service resource endpoint.
     *
     * @param businessId Id of the business
     * @param serviceId Id of the resource to update
     * @param data Map of data to change
     *
     * @return The updated Service
     * @throws FreshBooksException If the call is not successful
     */
    public Service update(long businessId, long serviceId, Map<String, Object> data) throws FreshBooksException {
        String url = this.getUrl(businessId, serviceId);
        ImmutableMap<String, Object> content = ImmutableMap.of("service", data);
        ProjectResponse result = this.handleRequest(HttpMethods.PUT, url, content);
        return result.service;
    }

    /**
     * Delete the service with the corresponding id.
     * Makes a DELETE call against the service resource endpoint.
     * <br><br>
     * <i>Note:</i> Most FreshBooks resources are soft-deleted,
     *
     * @param businessId Id of the business
     * @param serviceId Id of the resource to update
     *
     * @throws FreshBooksException If the call is not successful
     */
    public void delete(long businessId, long serviceId) throws FreshBooksException {
        String url = this.getUrl(businessId, serviceId);
        this.handleRequest(HttpMethods.DELETE, url);
    }
}
