package net.amcintosh.freshbooks.resources;

import com.google.api.client.http.HttpMethods;
import com.google.common.collect.ImmutableMap;
import net.amcintosh.freshbooks.FreshBooksClient;
import net.amcintosh.freshbooks.FreshBooksException;
import net.amcintosh.freshbooks.models.Task;
import net.amcintosh.freshbooks.models.TaskList;
import net.amcintosh.freshbooks.models.VisState;
import net.amcintosh.freshbooks.models.api.AccountingListResponse;
import net.amcintosh.freshbooks.models.api.AccountingResponse;
import net.amcintosh.freshbooks.models.builders.IncludesQueryBuilder;
import net.amcintosh.freshbooks.models.builders.QueryBuilder;
import net.amcintosh.freshbooks.resources.api.AccountingResource;

import java.util.List;
import java.util.Map;

/**
 * FreshBooks tasks resource with calls to get, list, create, update, delete
 */
public class Tasks extends AccountingResource {

    public Tasks(FreshBooksClient freshBooksClient) {
        super(freshBooksClient);
    }

    @Override
    protected String getPath() {
        return "projects/tasks";
    }

    /**
     * Get a list of tasks using the query strings generated by the QueryBuilder list.
     *
     * @param accountId Id of the account
     * @return TaskList containing tasks and pagination details
     * @throws FreshBooksException If the call is not successful
     */
    public TaskList list(String accountId) throws FreshBooksException {
        return this.list(accountId, null);
    }

    /**
     * Get a list of tasks using the query strings generated by the QueryBuilder list.
     *
     * @param accountId Id of the account
     * @param builders List of QueryBuilders
     * @return TaskList containing tasks and pagination details
     * @throws FreshBooksException If the call is not successful
     */
    public TaskList list(String accountId, List<QueryBuilder> builders) throws FreshBooksException {
        String url = this.getUrl(accountId, builders);
        AccountingListResponse result = this.handleListRequest(url);
        return new TaskList(result.response.result);
    }

    /**
     * Get a single task with the corresponding id.
     *
     * @param accountId The alpha-numeric account id
     * @param taskId Id of the resource to return
     *
     * @return The Task
     * @throws FreshBooksException If the call is not successful
     */
    public Task get(String accountId, long taskId) throws FreshBooksException {
        return this.get(accountId, taskId, null);
    }

    /**
     * Get a single task with the corresponding id.
     *
     * @param accountId The alpha-numeric account id
     * @param taskId Id of the resource to return
     * @param builder IncludesQueryBuilder object for including additional data, sub-resources, etc.
     *
     * @return The Task
     * @throws FreshBooksException If the call is not successful
     */
    public Task get(String accountId, long taskId, IncludesQueryBuilder builder) throws FreshBooksException {
        String url = this.getUrl(accountId, taskId, builder);
        AccountingResponse result = this.handleRequest(HttpMethods.GET, url);
        return result.response.result.task;
    }

    /**
     * Create a new task from the provided Task model.
     * Makes a POST call against the task resource endpoint.
     *
     * This calls `task.getContent()` to get a hash map of data.
     *
     * @param accountId The alpha-numeric account id
     * @param data Task model with create data
     *
     * @return The created Task
     * @throws FreshBooksException If the call is not successful
     */
    public Task create(String accountId, Task data) throws FreshBooksException {
        return this.create(accountId, data.getContent());
    }

    /**
     * Create a new task from the provided data.
     * Makes a POST call against the task resource endpoint.
     *
     * @param accountId The alpha-numeric account id
     * @param data Map of create data
     *
     * @return The created Task
     * @throws FreshBooksException If the call is not successful
     */
    public Task create(String accountId, Map<String, Object> data) throws FreshBooksException {
        String url = this.getUrl(accountId);
        ImmutableMap<String, Object> content = ImmutableMap.of("task", data);
        AccountingResponse result = this.handleRequest(HttpMethods.POST, url, content);
        return result.response.result.task;
    }

    /**
     * Update the task with the corresponding id.
     * Makes a PUT call against the task resource endpoint.
     *
     * @param accountId The alpha-numeric account id
     * @param taskId Id of the resource to return
     * @param data Task model with updated data
     *
     * @return The updated Task
     * @throws FreshBooksException If the call is not successful
     */
    public Task update(String accountId, long taskId, Task data) throws FreshBooksException {
        return this.update(accountId, taskId, data.getContent());
    }

    /**
     * Update the task with the corresponding id.
     * Makes a PUT call against the task resource endpoint.
     *
     * @param accountId The alpha-numeric account id
     * @param taskId Id of the resource to update
     * @param data Map of data to change
     *
     * @return The updated Task
     * @throws FreshBooksException If the call is not successful
     */
    public Task update(String accountId, long taskId, Map<String, Object> data) throws FreshBooksException {
        String url = this.getUrl(accountId, taskId);
        ImmutableMap<String, Object> content = ImmutableMap.of("task", data);
        AccountingResponse result = this.handleRequest(HttpMethods.PUT, url, content);
        return result.response.result.task;
    }

    /**
     * Delete the task with the corresponding id.
     * Makes a PUT call against the task resource endpoint with a `vis_state` of deleted.
     *
     * <i>Note:</i> Most FreshBooks resources are soft-deleted,
     * @see <a href="https://www.freshbooks.com/api/active_deleted">FreshBooks API - Active and Deleted Objects</a>
     *
     * @param accountId The alpha-numeric account id
     * @param taskId Id of the resource to update
     *
     * @return The deleted Task
     * @throws FreshBooksException If the call is not successful
     */
    public Task delete(String accountId, long taskId) throws FreshBooksException {
        ImmutableMap<String, Object> data = ImmutableMap.of("vis_state", VisState.DELETED.getValue());
        return this.update(accountId, taskId, data);
    }
}
