package net.amcintosh.freshbooks.resources;

import com.google.api.client.http.HttpMethods;
import com.google.common.collect.ImmutableMap;
import net.amcintosh.freshbooks.FreshBooksClient;
import net.amcintosh.freshbooks.FreshBooksException;
import net.amcintosh.freshbooks.models.*;
import net.amcintosh.freshbooks.models.api.AccountingListResponse;
import net.amcintosh.freshbooks.models.api.AccountingResponse;
import net.amcintosh.freshbooks.models.builders.IncludesQueryBuilder;
import net.amcintosh.freshbooks.models.builders.QueryBuilder;
import net.amcintosh.freshbooks.resources.api.AccountingResource;

import java.util.List;
import java.util.Map;

/**
 * FreshBooks taxes resource with calls to get, list, create, update, delete
 */
public class Taxes extends AccountingResource {

    public Taxes(FreshBooksClient freshBooksClient) {
        super(freshBooksClient);
    }

    @Override
    protected String getPath() {
        return "taxes/taxes";
    }

    /**
     * Get a list of taxes using the query strings generated by the QueryBuilder list.
     *
     * @param accountId Id of the account
     * @return TaxList containing taxes and pagination details
     * @throws FreshBooksException If the call is not successful
     */
    public TaxList list(String accountId) throws FreshBooksException {
        return this.list(accountId, null);
    }

    /**
     * Get a list of taxes using the query strings generated by the QueryBuilder list.
     *
     * @param accountId Id of the account
     * @param builders List of QueryBuilders
     * @return TaxList containing taxes and pagination details
     * @throws FreshBooksException If the call is not successful
     */
    public TaxList list(String accountId, List<QueryBuilder> builders) throws FreshBooksException {
        String url = this.getUrl(accountId, builders);
        AccountingListResponse result = this.handleListRequest(url);
        return new TaxList(result.response.result);
    }

    /**
     * Get a single tax with the corresponding id.
     *
     * @param accountId The alpha-numeric account id
     * @param taxId Id of the resource to return
     *
     * @return The Tax
     * @throws FreshBooksException If the call is not successful
     */
    public Tax get(String accountId, long taxId) throws FreshBooksException {
        return this.get(accountId, taxId, null);
    }

    /**
     * Get a single tax with the corresponding id.
     *
     * @param accountId The alpha-numeric account id
     * @param taxId Id of the resource to return
     * @param builder IncludesQueryBuilder object for including additional data, sub-resources, etc.
     *
     * @return The Tax
     * @throws FreshBooksException If the call is not successful
     */
    public Tax get(String accountId, long taxId, IncludesQueryBuilder builder) throws FreshBooksException {
        String url = this.getUrl(accountId, taxId, builder);
        AccountingResponse result = this.handleRequest(HttpMethods.GET, url);
        return result.response.result.tax;
    }

    /**
     * Create a new tax from the provided Tax model.
     * Makes a POST call against the tax resource endpoint.
     *
     * This calls `tax.getContent()` to get a hash map of data.
     *
     * @param accountId The alpha-numeric account id
     * @param data Tax model with create data
     *
     * @return The created Tax
     * @throws FreshBooksException If the call is not successful
     */
    public Tax create(String accountId, Tax data) throws FreshBooksException {
        return this.create(accountId, data.getContent());
    }

    /**
     * Create a new tax from the provided data.
     * Makes a POST call against the tax resource endpoint.
     *
     * @param accountId The alpha-numeric account id
     * @param data Map of create data
     *
     * @return The created Tax
     * @throws FreshBooksException If the call is not successful
     */
    public Tax create(String accountId, Map<String, Object> data) throws FreshBooksException {
        String url = this.getUrl(accountId);
        ImmutableMap<String, Object> content = ImmutableMap.of("tax", data);
        AccountingResponse result = this.handleRequest(HttpMethods.POST, url, content);
        return result.response.result.tax;
    }

    /**
     * Update the tax with the corresponding id.
     * Makes a PUT call against the tax resource endpoint.
     *
     * @param accountId The alpha-numeric account id
     * @param taxId Id of the resource to return
     * @param data Tax model with updated data
     *
     * @return The updated Tax
     * @throws FreshBooksException If the call is not successful
     */
    public Tax update(String accountId, long taxId, Tax data) throws FreshBooksException {
        return this.update(accountId, taxId, data.getContent());
    }

    /**
     * Update the tax with the corresponding id.
     * Makes a PUT call against the tax resource endpoint.
     *
     * @param accountId The alpha-numeric account id
     * @param taxId Id of the resource to update
     * @param data Map of data to change
     *
     * @return The updated Tax
     * @throws FreshBooksException If the call is not successful
     */
    public Tax update(String accountId, long taxId, Map<String, Object> data) throws FreshBooksException {
        String url = this.getUrl(accountId, taxId);
        ImmutableMap<String, Object> content = ImmutableMap.of("tax", data);
        AccountingResponse result = this.handleRequest(HttpMethods.PUT, url, content);
        return result.response.result.tax;
    }

    /**
     * Delete the tax with the corresponding id.
     * <br><br>
     * <i>Note:</i> Most FreshBooks resources are soft-deleted,
     * @see <a href="https://www.freshbooks.com/api/active_deleted">FreshBooks API - Active and Deleted Objects</a>
     *
     * @param accountId The alpha-numeric account id
     * @param taxId Id of the resource to update
     *
     * @throws FreshBooksException If the call is not successful
     */
    public void delete(String accountId, long taxId) throws FreshBooksException {
        String url = this.getUrl(accountId, taxId);
        this.handleRequest(HttpMethods.DELETE, url);
    }

}
