/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.amcintosh.freshbooks;

/**
 * Some thing that might be interesting, or might not.
 */
public class Library {
    /**
     *
     * @return stuff
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
